### ISSUE TITLE
HTTP Status 500 

### ISSUE THREAD

**Issue by BogdanAlinTudorache** [jrossi227/ApacheGUI#45]
I have tried installing ApacheGUI in a Raspberry pi 4, arm x64 and when trying to log into the user interface I get the below error.
I am running Ubuntu 20.04 and apache2.
```
ubuntu: conf/ :/usr/sbin/apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17
```
JAVA_HOME is set : 
```
ubuntu: conf/ :echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-arm64
```
Apache started
```
ubuntu: bin/ :sudo ./run.sh 
./run.sh: 1: [: -ne: unexpected operator
Using CATALINA_BASE:   /usr/local/apachegui/ApacheGUI/tomcat
Using CATALINA_HOME:   /usr/local/apachegui/ApacheGUI/tomcat
Using CATALINA_TMPDIR: /usr/local/apachegui/ApacheGUI/tomcat/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /usr/local/apachegui/ApacheGUI/tomcat/bin/bootstrap.jar:/usr/local/apachegui/ApacheGUI/tomcat/bin/tomcat-juli.jar
Tomcat started.
```

I tried a number of things but simply can't figure out what might be wrong.

ERROR when trying to access 192.169.1.31:9999/ApacheGUI
```

type Exception report

message

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.IllegalMonitorStateException
	java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryRelease(ReentrantReadWriteLock.java:372)
	java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302)
	java.base/java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.unlock(ReentrantReadWriteLock.java:1147)
	net.apachegui.locks.LockManager.unlockWrite(LockManager.java:181)
	net.apachegui.db.JdbcConnection.closeConnection(JdbcConnection.java:99)
	net.apachegui.db.SettingsDao.getAllSettings(SettingsDao.java:200)
	net.apachegui.db.SettingsDao.<init>(SettingsDao.java:28)
	net.apachegui.db.SettingsDao.getInstance(SettingsDao.java:36)
	net.apachegui.tomcat.ApacheGUIRealm.findSecurityConstraints(ApacheGUIRealm.java:13)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:834)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.85 logs.
```

**Comment by BogdanAlinTudorache** [comment]
And I think the issue is because of the architecture of the OS.
 _java.lang.Exception: No native library is found for os.name=Linux and os.arch=aarch64_

```
$ tail -f catalina.out:

16:52:17,938 ERROR JdbcConnection:59 - Error opening connection
java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at net.apachegui.db.JdbcConnection.getConnection(JdbcConnection.java:48)
	at net.apachegui.db.GuiJdbcConnection.getConnection(GuiJdbcConnection.java:16)
	at net.apachegui.db.SettingsDao.getAllSettings(SettingsDao.java:185)
	at net.apachegui.db.SettingsDao.<init>(SettingsDao.java:28)
	at net.apachegui.db.SettingsDao.getInstance(SettingsDao.java:36)
	at net.apachegui.tomcat.ApacheGUIRealm.findSecurityConstraints(ApacheGUIRealm.java:13)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:284)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:65)
	at org.sqlite.core.NativeDB.load(NativeDB.java:53)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	... 27 more
16:52:17,941 ERROR SettingsDao:196 - 
java.lang.NullPointerException
	at net.apachegui.db.SettingsDao.getAllSettings(SettingsDao.java:186)
	at net.apachegui.db.SettingsDao.<init>(SettingsDao.java:28)
	at net.apachegui.db.SettingsDao.getInstance(SettingsDao.java:36)
	at net.apachegui.tomcat.ApacheGUIRealm.findSecurityConstraints(ApacheGUIRealm.java:13)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
